---
- hosts: localhost
  tasks:
    - name: install dependecies
      apt: 
        name: "{{ item }}"
        state: latest
      with_items:
        - nodejs
        - git
        - gcc
        - make
